config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :recipes, only: [:index, :show, :create, :new, :destroy] do
    resources :recipe_foods, only: [:new, :destroy]
  end
  
  resources :recipe_foods, only: [:index, :edit, :update, :destroy, :create, :new]
  
  resources :public_recipes, only: %i[index]

  get 'shopping_list', to: 'shopping_list#index'

  root to: 'foods#index'
  resources :foods, only: [:index, :create, :new, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_scope :user do 
    authenticated :user do 
      root 'users#index', as: :authenticated_root 
    end
    unauthenticated do 
      root 'devise/sessions#new', as: :unauthenticated_root 
    end 
  end

  # Defines the root path route ("/")
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role == 'admin'
      can :manage, :all
    else
      can :manage, Recipe, user_id: user.id
      can :manage, Food, user_id: user.id
    end
    # can read recipes where public is true
    can :read, Recipe, public: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, :measurement_unit, :price, presence: true
  validates :price, numericality: { greater_than: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 1000 }
  validates :cooking_time, :preparation_time, numericality: { greater_than_or_equal_to: 0 }
  validates :public, inclusion: { in: [true, false] }

  def total_items
    recipe_foods.sum(:quantity)
  end

  def total_price
    recipe_foods.joins(:recipe, :food).sum('price * quantity')
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :food_id, presence: true, uniqueness: { scope: :recipe_id }
  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :recipes, dependent: :destroy
  has_many :foods, dependent: :destroy
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  load_and_authorize_resource
  before_action :set_food, only: %i[show destroy]

  def index
    if user_signed_in?
      @food = Food.includes(:user).where(user_id: current_user.id)
    else
      redirect_to user_session_path
    end
  end

  def new
    @food = Food.new
  end

  def create
    @food = current_user.foods.build(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_url, notice: 'Food was successfully created.' }
      else
        format.html { render :new, alert: 'Food could not be created' }
      end
    end
  end

  def destroy
    @recipes = RecipeFood.where(food_id: @food.id)
    @recipes.each(&:delete)
    @food.delete
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
    end
  end

  private

  def set_food
    @food = Food.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.includes(:user).where(public: true)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: %i[edit update destroy]
  before_action :set_foods, only: %i[edit new update]

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new
    @recipe_food.save
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)

    respond_to do |format|
      if @recipe_food.save
        format.html do
          redirect_to recipe_path(@recipe_food.recipe), notice: 'Recipe food was successfully created.'
        end
      else
        set_foods
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe_food.update(recipe_food_params)
        format.html do
          redirect_to recipe_path(recipe_food_params[:recipe_id]), notice: 'Recipe food was successfully updated.'
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    flash[:success] = 'Recipe Food deleted successfully.'
    redirect_to recipe_path(@recipe_food.recipe_id)
  end

  private

  def set_foods
    @foods = current_user.foods.map { |food| [food.name, food.id] }
  end

  def set_recipe_food
    @recipe_food = RecipeFood.includes(:recipe, :food).find(params[:id])
  end

  def recipe_food_params
    params.fetch(:recipe_food, {}).permit(:quantity, :food_id, :recipe_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource
  def index
    @recipes = Recipe.includes(:user).where(user_id: current_user.id)
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    respond_to do |format|
      format.html do
        if @recipe.save
          redirect_to recipes_url, notice: 'Recipe was successfully created.'
        else
          render :new, alert: 'Recipe could not be created'
        end
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = 'Recipe deleted successfully'
    redirect_to recipes_url
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  before_action :authenticate_user!
  include ShoppingListHelper

  def index
    @recipes = Recipe.includes(:user).where(user_id: current_user.id)
    @foods = foods_join
    @total_price = 0
    @recipes.each do |recipe|
      @total_price += recipe.total_price
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper
  def foods_join
    # rubocop:disable Lint/UselessAssignment
    foods_join = Food.joins(:recipe_foods).where(user_id: current_user.id)
    # rubocop:enable Lint/UselessAssignment
  end
end

app/views/foods/_form.html.erb
<div class="container food-form">

<%= form_with(model: food) do |form| %>
  <div class="card form">
    <div class="card-body">
      <div class="mb-3">
        <%= form.label :name, class: "form-label" %>
        <div>
          <%= form.text_field :name, autofocus: true, class: "form-control", required: true %>
        </div>
      </div>

      <div>
        <%= form.label :measurement_unit, class: "form-label" %>
        <div>
          <%= form.text_field :measurement_unit, autofocus: true, class: "form-control", required: true %>
        </div>
      </div>

      <div>
        <%= form.label :price, class: "form-label" %>
        <div>
          <%= form.number_field :price, autofocus: true, class: "form-control", required: true, min: 1 %>
        </div>
      </div>

      <br>

      <div>
        <%= form.submit class: "btn btn-info" %>
      </div>
    </div>
  </div>
<% end %> 

app/views/foods/index.html.erb
<div class="container">
  <h1>Foods list</h1>
  
  <% if @food.size == 0 %>
    <p>No foods have been added yet.</p>
  <% else %>
    <table class="table table-bordered table-hover">
      <thead class="table-dark">
        <tr>
          <th>Food</th>
          <th>Measurement unit</th>
          <th>Unit price</th>
          <th>Actions</th>
        </tr>
      </thead>
    
      <tbody>
        <% @foods.each do |food| %>
          <tr>
            <th class="align-middle"><%= food.name %></th>
            <td class="align-middle"><%= food.measurement_unit %></td>
            <td class="align-middle">$<%= food.price %></td>
            <td class="align-middle"><%= button_to 'Delete', food_url(food), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  
  <br>
  
  <%= link_to 'Add Food', new_food_path, class: "btn btn-info"%>
</div>

app/views/foods/new.html.erb
<div  class="container">
  <div class="text-center">
		<h1>Add new food</h1>
	</div>
		<%= render 'form', food: @food %>
		<div class="text-center">
		<%= link_to 'Back', url_for(:back) %>
		</div>
	</div>
</div>

app/views/layouts/_alerts.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>

<div class="alert alert-success d-flex align-items-center" role="alert">
  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
  <%= notice %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>RecipeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <%= render 'navbar/navbar' %>

    <div class="container">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
    </div>
    <%= yield %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/navbar/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="margin-bottom: 2rem;">
  <div class="container-fluid">
    <%= link_to  "Recipe App", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to  "Public-Recipes", public_recipes_path, class:"nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to  "Foods", foods_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to  "My-Recipes", recipes_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Shopping-list", shopping_list_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to  "Edit-Profile", edit_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to  "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link-info btn btn-outline-light" %>
          </li>
        <% else  %>
          <li class="nav-item">
            <%= link_to  "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to  "Sign In", new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/public_recipes/index.html.erb
<div class="container">
  <h1 class="bio text-center">Public Recipes</h1>
​
  <div>
    <% if @recipes.size > 0 %>
    <% @recipes.each do |recipe|%>
      <div class="border border-info rounded row" style="max-width: 850px; margin: 1rem auto;">
        <div class="col d-flex align-items-center justify-content-evenly flex-column" style="padding: 2.5rem;">
          <%= link_to recipe_path(recipe.id), id: "recipe_path#{recipe.id}" do %>
          <h5 class="text-dark"><%= recipe.name%></h5>
          <% end %>
​
          <p class="mt-6">By: <%= User.find_by(id: recipe.user_id).name%></p>
        </div>
        <div class="col d-flex align-items-center justify-content-evenly flex-column" style="padding: 1.5rem;">
          <p> Total food items: <%= @recipes.length %> </p>
          <p class="mt-6"> Total price: $<%= recipe.total_price %> </p>
        </div>
      </div>
    <%end%>
    <% else %>
    <p class="border border-2">There are no public recipes yet!!</p>
    <% end %>
  </div>
</div>

app/views/recipe_foods/_form.html.erb
<%= form_with(model: recipe_food) do |form| %>
  <div class="field container">
    <%= form.label :food, class: "form-label" %>
    <div>
      <%= form.select :food_id, @foods, class:"form-select" %>
    </div>
  </div>

  <div class="field container">
    <%= form.label :quantity, class: "form-label" %>
    <div class="control">
      <%= form.text_field :quantity, class: "form-control", type: "number", required: true, min: 1 %>
    </div>
  </div>

  <%= form.hidden_field :recipe_id, value: recipe_food.recipe_id %>

  <div class="container p-3">
    <%= form.submit class: "btn btn-info" %> ||
    <%= link_to 'Back', url_for(:back), class: "btn btn-info" %>
  </div>
<% end %>

app/views/recipe_foods/_index.html.erb
<% if @recipe.recipe_foods %>
<div class="table-container">
  <table class="table table-bordered table-hover">
    <thead class="table-info">
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @recipe.recipe_foods.each do |recipe_food| %>
        <tr>
          <th class="align-middle"><%= recipe_food.food.name %></th>
          <td class="align-middle"><%= pluralize(recipe_food.quantity, recipe_food.food.measurement_unit) %></td>
          <td class="align-middle">$<%= recipe_food.quantity * recipe_food.food.price %></td>
			    <% if can? :update, recipe_food.recipe %>
            <td>
              <div class="d-flex">
                <%= link_to 'Edit', edit_recipe_food_path(recipe_food), class: "btn btn-warning btn-sm" %> ||
                <%= button_to "Delete", recipe_recipe_food_path(@recipe, recipe_food), method: :delete, class: "btn btn-danger btn-sm"%>
              </div>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
</div>
<% end %>

app/views/recipe_foods/edit.html.erb
<div class="container w-50">
  <div class="column is-two-fifths-desktop">
		<h3 class="title is-4 text-center pb-3">Edit Ingredient</h3>
		<div class="card">
      <div class="card-body">
        <%= render 'form', recipe_food: @recipe_food %>
      </div>
		</div>
	</div>
</div>

app/views/recipe_foods/new.html.erb
<div class="container w-50 text-center">

<%= form_with(model: @recipe_food) do |form| %>
  <div class="card form">
  <div class="card-body">
  <div class="field container">
    <%= form.label :food, class: "form-label p-2" %>
    <div class="select">
      <%= form.select :food_id, @foods, class: "form-select"  %>
    </div>
  </div>

  <div class="field container">
    <%= form.label :quantity, class: "form-label p-2" %>
    <div class="control">
      <%= form.text_field :quantity, class: "form-control", type: "number", required: true, min: 1 %>
    </div>
  </div>

  <%= form.hidden_field :recipe_id, value: @recipe_food.recipe_id %>

  <div class="actions rf-btn p-3">
    <%= form.submit class: "btn btn-primary btn-floating mx-1" %>
  </div>
</div>
</div>
<% end %>

</div>

app/views/recipes/_form.html.erb
<div class="fs-4 p-3 border border-1 container mt-5 p-2 bio">
  <%= form_with(model: recipe) do |f| %>
    <% if recipe.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
  
        <ul>
          <% recipe.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <h1> New Recipe </h1>
  
    <div>
      <%= f.label :name, "Name", class: "form-label fs-6" %><br>
      <%= f.text_field :name, :placeholder => "Add Your Recipe name here...", required: true, class: "form-control" %><br>
    </div>

    <div>
      <%= f.label :description, "Write description", class: "form-label fs-6" %>
      <%= f.text_area :description, size: "80x7", :placeholder => "Add your description here...", required: true, class: "form-control" %>
    </div>

    <div>
      <%= f.label :cooking_time, "Cooking time(mins)", class: "form-label fs-6" %>
      <%= f.number_field :cooking_time, class: "form-control mb-2" %>
    </div>

    <div>
      <%= f.label :preparation_time, "Preparation time(mins)", class: "form-label fs-6", min:"0" %>
      <%= f.number_field :preparation_time, class: "form-control mb-2", min:"0" %>
    </div>
    
    <div class="form-check form-switch" style="margin:1rem 0;">
        <%= f.label :public, for:'flexSwitchCheckDefault', class:"form-check-label" %>
        <%= f.check_box :public, class:'form-check-input', id:"flexSwitchCheckDefault", role:"switch" %>
    </div>
  
    <div>
      <%= f.submit "Create Recipe", class:"btn btn-outline-info" %> |
      <%= link_to "Back to recipes", recipes_path, class:"btn btn-outline-info" %>
    </div>
  <% end %>
</div>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Name:</strong>
    <%= recipe.name %>
  </p>

  <p>
    <strong>Preparationtime:</strong>
    <%= recipe.preparation_time %>
  </p>

  <p>
    <strong>Cookingtime:</strong>
    <%= recipe.cooking_time %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

  <p>
    <strong>Public:</strong>
    <%= recipe.public %>
  </p>

</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <div class="is-flex is-justify-content-end my-6">
    <%= link_to 'Create Recipe', new_recipe_path, class: "btn btn-dark cr-btn" %>
  </div>
  <ul style="padding: 2rem 0 0 0;">
    <% if @recipes.size > 0%>
      <% @recipes.each do |r| %>
        <li class="card mb-3" >
          <div class="row">
            <div class="col-3 card-body" >
              <%= link_to recipe_path(r.id), id: "recipe_path#{r.id}" do %>
              <h4 class="text-dark text-center" style="margin-bottom: 2.5rem;"><%= r.name%></h4>
              <% end %>
              <% if can? :delete, r %>
                <div class="d-grid gap-2 col-6 mx-auto" style="margin-top: 0.7rem;">
                  <%= button_to "Remove", recipe_path(r.id), method: :delete, class: "btn btn-info"%>
                </div>
              <% end %>
            </div>
            <div class="col-9" >
              <div class="card-body">
                <p class="card-text"><%= r.description%></p>
                <p class="card-text text-end"><small class="text-muted"><%= r.updated_at%></small></p>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    <% else %>
      <p class="border border-2 container mt-5 p-2 bio px-5 fs-1">There are no recipes registered!</p>
    <% end %>
  </ul>
</div>

app/views/recipes/new.html.erb
<%= render "form", recipe: @recipe %>

app/views/recipes/show.html.erb
<div class="border border-2 border-info container p-2 my-5 rounded" style="padding: 5rem;">
  <div class="my-3 text-center">
    <h2 class><%= @recipe.name%></h2>
  </div>
  <div>
    <div class="split">
      <div class="d-flex justify-content-between p-2">
        <h5> Preparation time: <%= @recipe.preparation_time %> minutes </h5>
        <div class="form-check form-switch">
          <% if @recipe.public %>
            Public <input type="checkbox" checked="true" class="form-check-input" role="switch" id="flexSwitchCheckedDefault" >
          <% end %>
          <% if !@recipe.public %>
            Public <input type="checkbox" class="form-check-input" role="switch" id="flexSwitchCheckDefault"  >
          <% end %>
        </div>
      </div>
    </div>
    <div>
      <h5 class="p-2"> Cooking time: <%= @recipe.cooking_time %> minutes </h5>
      <h5 class="p-2"> <%= @recipe.description %></h5>
    </div>
    
    <% if user_signed_in? %>
      <div class="d-flex justify-content-around" style="margin-bottom: 2rem;">
        <div class="w-30">
          <%= link_to "Generate shopping list", shopping_list_path, class: "btn btn-info"%>
        </div>
        <% if can? :update, @recipe %>
          <div>
            <%= link_to 'Add ingredient', new_recipe_recipe_food_path(@recipe), class: "btn btn-info" %>
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="column is-three-quarters">
      <%= render partial: "recipe_foods/index", locals: { recipe_foods: @recipe } %>
    </div>
  </div>
</div>

app/views/shopping_list/_table.html.erb
<% qty=RecipeFood.joins(:food).where(food_id: food.id).sum('quantity') %>
<tr>
    <td class="align-middle">
      <%=food.name %>
    </td>
    <td class="align-middle">
      <%= qty %>
    </td>
    <td class="align-middle">$
      <%=food.price * qty %>
    </td>
</tr> 

app/views/shopping_list/index.html.erb
<div class="container border border-2 rounded w-50">
    <div class="column is-half has-text-centered p-4">
        <h1 class="title text-center">Shopping List</h1>
        <div class="columns container d-flex justify-content-around p-2">
            <div class="column p-3">
                <p>Amount of food items to buy: <%= @foods.count %></p>
            </div>
            <div class="column p-3">
                <p>Total value of food needed: $ <%= @total_price %></p>
            </div>
        </div>
    </div>
    <table class="table table-bordered">
        <thead class="table-dark">
            <tr>
            <th>Food</th>
            <th>Quantity</th>
            <th>Price</th>
            </tr>
        </thead>
        <tbody>
            <% @foods.each do |food| %>
              <%= render 'table', food: food %>
            <% end %>
        </tbody>
    </table>
</div>